project:
  type: website

website:
  title: "the_engi_nerd"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/the-engi-nerd
      - icon: twitter
        href: https://twitter.com/the_engi_nerd
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

